my_string = input('Введите пароль ввиде слова:')
print('Пароль принят:', my_string)
print('Хорошего дня:', my_string.upper())
print('Хорошего дня:', my_string.lower())
print('Хорошего дня:'.replace('Хорошего', 'Прекрасного'), 'Ваш пароль :', my_string)
print('Прекрасного дня и удачи:'.replace(' ', ''))
print(my_string[0])
print(my_string[-1])
